### ISSUE TITLE
Implement RDGameplayPatches into the base game

### ISSUE THREAD

**Issue by RandomGuyJCI** [7thbeatgames/rd#38]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

After developing my RDGameplayPatches plugin over the course of a few months, I can say that I added almost all of the tweaks and fixes I wanted for RD gameplay. As such, I think would be best if the majority of the patches I made were ported over to the main game. This issue mainly serves as a todo list of patch suggestions.

### Suggestion / Solution

The patches can be sorted into three categories:

### Need to haves:
- [x] **Anti-cheese holds, Fix Auto-Hit Misses, & Fix Hold Pseudos**
    - As it currently stands, the hold mechanic is pretty underdeveloped. These three patches combined pretty much fixes all of the issues players have with hold auto-hits and would finally allow the use of pseudo-hits without being unfair.
- [x] **2P Keyboard Layout**
    - Adding 2P keyboard layout as an option in the settings would be really helpful for people with alternative keyboard layouts when playing 2P levels. They would no longer need to switch to QWERTY or memorize which keys correspond to which player.

### Nice to haves:
- [ ] **Count Offset On Release**
    - Getting the hold release offset would be really useful, although my patch does not have a limit on how high the offset could be (e.g. releasing extremely early on a long hold beat), which could lead to problems.
- [x] **Rank Color On Speed Change & Change Rank Button Per Difficulty**
    - While not strictly necessary, changing the text color & button on the rank screen would be a nice detail to add, and it eliminates the need to show the pause menu to show that you played on a speed trial.
- [ ] **Status Sign Transparency**
    - Having the status sign transparency as a configurable option in the settings can help with visibility, since the sign usually obstructs the gameplay behind it.

### Not really needed:
- **Accurate Release Margins:** This is not really a needed suggestion since having the release margins be more lenient may be intended by the developers.
- **Legacy Hit Judgment:** The current rounding system of the hit judgment is still precise enough, and putting back the three decimal places can just be done in a plugin like this one. Having this as an accessibility setting can still be considered, though.
- **Very Hard:** As much as I would like a Very Hard difficulty setting to be added to the game, I understand that it can be seen as an unfair challenge for most players. Therefore, I'm fine with keeping this as its own mod.

### Demo & Mockup

For the full details of my patches, see https://github.com/RandomGuyJCI/RDGameplayPatches#features .

### Note

Side note: A few months ago, Jose has informed me that the devs were looking on the fixes I made on my plugin. However, considering that he is no longer in the dev team and there were no other news after that, I decided to make this Github issue as a follow-up.

**Comment by RandomGuyJCI** [comment]
Since most of these suggestions have now been implemented in dev, I'll be closing this issue
